### ISSUE TITLE
PathTooLongException

### ISSUE THREAD

**Issue by perp1exed** [johanclasson/vso-agent-tasks#25] opened 2017-07-18 16:00 UTC
Attempting to deploy scripts using VS database prodject. Script set to Not Build.

I get the error: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

The longest file path is 108 chracters so not sure why this is occurring.

Here is the longest file path: E:\vstsagent\_work\975ffc9f4\ITXDB.MAIN\Database_Scripts\1. UID Updates\MatterTypeCategoriesUpdateScript.sql

Any help appreciated.

thanks,
KS

**Comment by johanclasson** [comment] 2017-08-08 07:59
I have not been able to reproduce this. Can you link me to your solution (example or real one) so I can investigate?

**Comment by perp1exed** [comment] 2017-08-11 20:28
[ITX Database.zip](https://github.com/johanclasson/vso-agent-tasks/files/1219001/ITX.Database.zip)

Attached is solution. Thank you.

**Comment by johanclasson** [comment] 2017-08-12 06:55
The solution you provided contained scripts that depend on that there would already be some tables present...

But as a work around a cleared all *.sql-scripts from content, and ran them through the DbUpMigration task. And everything seamed to work.

In my case the paths were even longer than your example obove (129 chars at max).

```
...
C:\git\vso-agent-tasks\DbUpMigration\test\sql\long\ITXDatabaseUpdate_07052017\1. UID Updates\MatterStatusUpdateScript.sql
C:\git\vso-agent-tasks\DbUpMigration\test\sql\long\ITXDatabaseUpdate_07052017\1. UID Updates\MatterTypeCategoriesUpdateScript.sql
C:\git\vso-agent-tasks\DbUpMigration\test\sql\long\ITXDatabaseUpdate_07052017\1. UID Updates\MatterTypesUpdateScript.sql
C:\git\vso-agent-tasks\DbUpMigration\test\sql\long\ITXDatabaseUpdate_07052017\1. UID Updates\MediaActivitiesUpdateScript.sql
C:\git\vso-agent-tasks\DbUpMigration\test\sql\long\ITXDatabaseUpdate_07052017\1. UID Updates\NuancesUpdateScript.sql
...
```

I have a theory that something powershelly works different on your build server that runs the task than on my machine. Can you execute `$PSVersionTable` in a powershell-console and post its content for me?

Here is mine:
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Or do you run the task on the VSTS Hosted Build Agents?

**Comment by johanclasson** [comment] 2018-04-16 09:28
Since I have not heard any more about this error, or been able to reproduce it i will close this. Please reopen if you are still having this issue!

**Closed by johanclasson** 2018-04-16 09:28 UTC
